version: '3'
services:
  landing_page:
    image: php:7.2-apache
    container_name: landing_page
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html/
    command: bash -c "apache2-foreground"