version: '3'
services:
  web:
    image: webserver:1.0-tresnax
    container_name: webserver
    ports:
      - "8080:80"
  
  apps:
    image: todolist:latest
    container_name: app-todolist
    ports:
      - "8000:8000"